# Generated by Django 5.0.4 on 2024-05-01 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_refreshtokenmodel_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtokenmodel",
            name="expires_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 31, 21, 21, 20, 851620, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
