# Generated by Django 5.0.4 on 2024-05-15 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_refreshtoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtokenmodel",
            name="token",
        ),
    ]
