# Generated by Django 5.0.4 on 2024-05-27 19:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_remove_refreshtokenmodel_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="refreshtokenmodel",
            name="user",
        ),
        migrations.DeleteModel(
            name="RefreshToken",
        ),
        migrations.DeleteModel(
            name="RefreshTokenModel",
        ),
    ]
